var FanweShou;FanweShou||(FanweShou={});
(function(){FanweShou.browserType=!!window.ActiveXObject;FanweShou.url="http://demo.yaojingmao.com/";FanweShou.domain="yaojingmao.com";FanweShou.siteName="方维";FanweShou.imgWidth=200;FanweShou.imgHeight=120;"function"!==typeof FanweShou.init?(FanweShou.init=function(){if(FanweShou.getDomain()==FanweShou.domain)return alert("\u4eb2\uff0c\u4f60\u5c31\u5728 "+FanweShou.siteName+" \u5462\uff0c\u4e0d\u80fd\u5206\u4eab\u672c\u7ad9\u7684\u56fe\u7247\u54e6\uff01"),!1;FanweShou.isCancel=!1;FanweShou.ShouBox||(FanweShou.setCss(),
FanweShou.ShouBg=document.createElement("div"),FanweShou.ShouBg.id="FANWE_SHOU_BG",document.body.appendChild(FanweShou.ShouBg),FanweShou.ShouBox=document.createElement("div"),FanweShou.ShouBox.id="FANWE_SHOU_BOX",document.body.appendChild(FanweShou.ShouBox),FanweShou.CheckPageBox=document.createElement("div"),FanweShou.CheckPageBox.className="FSB_CHECK_PAGE",FanweShou.CheckPageBox.innerHTML='\u4eb2\uff0c\u6b63\u5728\u68c0\u6d4b\u9875\u9762\u4e2d\uff0c\u8bf7\u7a0d\u5019...<a class="FSBCP_CLOSE" href="javascript:;" onclick="FanweShou.cancel()"></a>',
FanweShou.ShouBox.appendChild(FanweShou.CheckPageBox),FanweShou.Toolbar=document.createElement("div"),FanweShou.Toolbar.id="FANWE_SHOU_TOOLBAR",FanweShou.Toolbar.innerHTML='<img class="FST_LOGO" id="FST_LOGO" src="'+FanweShou.url+'shou/logo.png" /><a class="FST_CANCEL" href="javascript:;" onclick="FanweShou.cancel()"></a>',document.body.appendChild(FanweShou.Toolbar),FanweShou.ImageBox=document.createElement("div"),FanweShou.ImageBox.className="FSB_IMG_BOX",FanweShou.ShouBox.appendChild(FanweShou.ImageBox),
FanweShou.ShouIframe=document.createElement("iframe"),FanweShou.ShouIframe.width="100%",FanweShou.ShouIframe.height="100%",FanweShou.ShouIframe.allowTransparency=!0,FanweShou.ShouIframe.frameBorder=0,FanweShou.ShouIframe.scrolling="no",FanweShou.ShouBox.appendChild(FanweShou.ShouIframe),FanweShou.addIframeEvent());FanweShou.ImageBox.innerHTML="";FanweShou.ImageBox.style.display="none";FanweShou.ShouBg.style.display="block";FanweShou.ShouBox.style.display="block";FanweShou.Toolbar.style.display="none";
FanweShou.ShouIframe.style.display="none";FanweShou.CheckPageBox.style.display="block";FanweShou.CheckPageBox.style.left=(FanweShou.ShouBox.offsetWidth-306)/2+"px";FanweShou.checkImgs()},FanweShou.setCss=function(){var a=document.head||document.getElementsByTagName("head")[0],b="#FANWE_SHOU_BG{background-color:#f2f2f2; height:100%; width:100%; left:0px; top:0px; zoom:1; position:fixed; z-index:2147483580; opacity:0.8; FILTER:alpha(opacity=80);}#FANWE_SHOU_BOX{height:100%; width:100%; left:0px; top:0px; zoom:1; position:absolute; z-index:2147483581;}#FANWE_SHOU_BOX *{font-size:12px;}#FANWE_SHOU_BOX iframe{position:fixed; left:0; top:0; background:transparent; display:none;}#FANWE_SHOU_BOX .FSB_CHECK_PAGE{-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;border:dashed 3px #ff277d; width:220px; height:80px; background:url("+
FanweShou.url+"shou/loading.gif) no-repeat 16px center #ffe8f0; padding:0 0 0 80px;font-size:14px;line-height:80px; position:fixed; top:100px; display:none;}#FANWE_SHOU_BOX .FSBCP_CLOSE{display:block; width:13px; height:13px;background:url("+FanweShou.url+"shou/closem.png) no-repeat; position:absolute; top:6px; right:6px;}#FANWE_SHOU_TOOLBAR{height:75px; width:100%; left:0px; top:0px; zoom:1; position:fixed; z-index:2147483582; background:url("+FanweShou.url+"shou/toolbar.png) repeat-x; _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+
FanweShou.url+"shou/toolbar.png', sizingMethod='scale'); _background:none; display:none;}#FANWE_SHOU_TOOLBAR .FST_LOGO{height:50px; float:left; margin:8px 0 0 8px;}#FANWE_SHOU_TOOLBAR .FST_CANCEL{display:block; width:69px; height:31px;background:url("+FanweShou.url+"shou/close.png) no-repeat; float:right; margin:16px 20px 0 0;}#FANWE_SHOU_BOX .FSB_IMG_BOX{float:left; border-top:1px solid #E7E7E7;border-left: 1px solid #E7E7E7;margin:75px 0 0 0;}#FANWE_SHOU_BOX .FSBIB_ITEM{border-right: 1px solid #E7E7E7;border-bottom: 1px solid #E7E7E7;padding:4px;float: left;position:relative;background: white;text-align:center;overflow:hidden; text-decoration:none;}#FANWE_SHOU_BOX .FSBIB_ITEM img{border:0; vertical-align:middle;}#FANWE_SHOU_BOX .FSBIB_ITEM input{border:none; width:129px; height:32px; background:url("+
FanweShou.url+"shou/publish.png) no-repeat; padding:0; position:absolute;cursor:pointer; display:none; text-indent:-200px; overflow:hidden;}#FANWE_SHOU_BOX .FSBIB_ITEM:hover input{display:block;}#FANWE_SHOU_BOX .FSBIB_ITEM em{font-style: normal;font-size: 10px;font-family: Arial;position: absolute;bottom:10px;text-align: center;width: 85px;height: 21px;z-index: 1000;background: url("+FanweShou.url+"shou/size.png) no-repeat;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+FanweShou.url+
"shou/size.png', sizingMethod='scale'); _background:none;line-height: 21px;z-index: 1; color:#000;}";FanweShou.ShouStyle||(FanweShou.ShouStyle=document.createElement("style"),FanweShou.ShouStyle.type="text/css",FanweShou.ShouStyle.media="screen",a.appendChild(FanweShou.ShouStyle));FanweShou.browserType?FanweShou.ShouStyle.styleSheet.cssText=b:FanweShou.ShouStyle.innerHTML=b},FanweShou.addIframeEvent=function(){FanweShou.IframeHandler=null;window.postMessage?(FanweShou.IframeHandler=function(a){a=
a||window.event;-1<a.data.indexOf("publish")?FanweShou.checkPublish(a.data):"getimgs"==a.data?FanweShou.ShouIframe.contentWindow.postMessage(FanweShou.postImgs,"*"):"close"==a.data&&(FanweShou.cancel(),window.addEventListener?window.removeEventListener("message",FanweShou.IframeHandler,!1):window.detachEvent("onmessage",FanweShou.IframeHandler))},window.addEventListener?window.addEventListener("message",FanweShou.IframeHandler,!1):window.attachEvent("onmessage",FanweShou.IframeHandler)):FanweShou.IframeHandler=
window.setInterval(function(){-1<FanweShou.ShouIframe.contentWindow.name.indexOf("publish")?FanweShou.checkPublish(FanweShou.ShouIframe.contentWindow.name):"close"==FanweShou.ShouIframe.contentWindow.name&&(FanweShou.cancel(),window.clearInterval(FanweShou.IframeHandler))},500)},FanweShou.checkPublish=function(a){var a=a.split(","),b=a[2];"g"==a[1]?1==b?FanweShou.publishGoods():(FanweShou.cancel(),0==b?alert("\u4eb2\uff0c\u6ca1\u6709\u83b7\u53d6\u5546\u54c1\u4fe1\u606f\uff0c\u7b49\u4f1a\u518d\u5206\u4eab\u8be5\u5546\u54c1\u5427\uff01"):
-1==b?alert("\u4eb2\uff0c\u4f60\u5df2\u5206\u4eab\u8fc7\u8fd9\u4e2a\u5546\u54c1\u4e86\u54e6\uff01"):-2==b?alert("\u4eb2\uff0c"+FanweShou.siteName+" \u7981\u6b62\u53d1\u5e03\u8fd9\u4e2a\u5546\u54c1\uff0c\u5206\u4eab\u5176\u4ed6\u5546\u54c1\u5427\uff01"):-3==b?alert("\u4eb2\uff0c\u8be5\u5e97\u94fa\u7684\u5546\u54c1\u5df2\u88ab\u7981\u6b62\u5206\u4eab\uff0c\u5206\u4eab\u5176\u4ed6\u5e97\u94fa\u7684\u5546\u54c1\u5427\uff01"):-4==b&&alert("\u4eb2\uff0c\u8fd9\u79cd\u5206\u7c7b\u7684\u5546\u54c1\u5df2\u88ab\u7981\u6b62\u5206\u4eab\uff0c\u5206\u4eab\u5176\u4ed6\u5206\u7c7b\u7684\u5546\u54c1\u5427\uff01")):
(0==b?alert("\u4eb2\uff0c\u5206\u4eab\u56fe\u7247\u53d1\u751f\u9519\u8bef\uff0c\u518d\u5206\u4eab\u4e00\u6b21\u5427\uff01"):-1==b?alert("\u4eb2\uff0c\u6ca1\u80fd\u83b7\u53d6\u4f60\u5206\u4eab\u7684\u56fe\u7247\uff0c\u5206\u4eab\u5176\u4ed6\u56fe\u7247\u5427\uff01"):-2==b&&alert("\u4eb2\uff0c\u4f60\u5206\u4eab\u7684\u56fe\u7247\u592a\u5927\u4e86\uff0c\u5206\u4eab\u5176\u4ed6\u56fe\u7247\u5427\uff01"),FanweShou.showImgs())},FanweShou.getDomain=function(){var a=window.location.href.match(/:\/\/([^/]*)(?:\/)?/);
a&&(a=a[1].split("."),a.shift(),a=a.join("."));return a},FanweShou.cancel=function(){FanweShou.isCancel=!0;FanweShou.ImageBox.innerHTML="";FanweShou.ImageBox.style.display="none";FanweShou.Toolbar.style.display="none";FanweShou.ShouIframe.style.display="none";FanweShou.CheckPageBox.style.display="none";FanweShou.ShouBg.style.display="none";FanweShou.ShouBox.style.display="none"},FanweShou.publishGoods=function(){FanweShou.isCancel||(FanweShou.ShouIframe.style.display="block",FanweShou.CheckPageBox.style.display=
"none",FanweShou.ShouIframe.src=FanweShou.url+"shou.php?type=g&href="+encodeURIComponent(window.location.href)+"&t="+(new Date).getTime())},FanweShou.publishPhoto=function(a,b,c){FanweShou.isCancel||(FanweShou.ShouIframe.style.display="block",FanweShou.Toolbar.style.display="none",FanweShou.ImageBox.style.display="none",FanweShou.ShouIframe.src=FanweShou.url+"shou.php?type=p&href="+a+"&w="+b+"&h="+c+"&t="+(new Date).getTime())},FanweShou.showImgs=function(){FanweShou.ShouIframe.style.display="none";
FanweShou.CheckPageBox.style.display="none";FanweShou.Toolbar.style.display="block";FanweShou.ImageBox.style.display="block";document.body.scrollTop=0;if(FanweShou.imgs){for(var a,b,c,d,g,j,f,k,e=FanweShou.getImgWidthByPage()-1,h="",i=0;i<FanweShou.imgs.length;i++)a=FanweShou.imgs[i],e/a.width>e/a.height?(b=e/a.height,d=e,g=a.width*b):(b=e/a.width,g=e,d=a.height*b),b=(e-g)/2,c=(e-d)/2,j=(e-129)/2,f=(e-32)/2,k=(e-85)/2,h+='<a class="FSBIB_ITEM" href="javascript:;" style="width:'+e+"px;height:"+e+'px;" rel="'+
encodeURIComponent(a.src)+'"><img style="width:'+g+"px;height:"+d+"px;margin-top:"+c+"px;margin-left:"+b+'px;" src="'+a.src+'"><input type="button" value="\u53d1\u5e03" style="left:'+j+"px;top:"+f+'px;" onclick="FanweShou.publishPhoto(\''+encodeURIComponent(a.src)+"',"+a.width+","+a.height+')"/><em style="left:'+k+'px;">'+a.width+"x"+a.height+"</em></a>";FanweShou.imgs=null;FanweShou.ImageBox.innerHTML=h}},FanweShou.getImgWidthByPage=function(){var a=window.document.body.offsetWidth-1,b=Math.ceil(a/
(FanweShou.imgWidth+9));return a/b},FanweShou.checkImgs=function(){var a=document.getElementsByTagName("img"),b=a.length;FanweShou.imgs=[];FanweShou.postImgs="";for(var c={},d=0;d<a.length&&!FanweShou.isCancel;d++)a[d]&&a[d].src?c[encodeURIComponent(a[d].src)]?b--:(c[encodeURIComponent(a[d].src)]=!0,FanweShou.getImgSize(a[d].src,function(a,d,f){d>=FanweShou.imgWidth&&f>=FanweShou.imgHeight&&(FanweShou.postImgs=""==FanweShou.postImgs?FanweShou.postImgs+('[{"width":'+d+',"height":'+f+',"src":"'+encodeURIComponent(a)+
'"}'):FanweShou.postImgs+(',{"width":'+d+',"height":'+f+',"src":"'+encodeURIComponent(a)+'"}'),FanweShou.imgs.push({width:d,height:f,src:a}));b--;0==b&&(c=null,delete c,0<FanweShou.imgs.length?(FanweShou.postImgs+="]",FanweShou.checkPage()):(FanweShou.cancel(),alert("\u4eb2\uff0c\u9875\u9762\u4e0a\u56fe\u7247\u90fd\u592a\u5c0f\u4e86\u54e6\uff01")))})):b--},FanweShou.getImgSize=function(a,b){var c=new Image,d=!1;c.onload=function(){d||(b.call(this,a,c.width,c.height),c.onload=null,c.onerror=null,delete c)};
c.onerror=function(){d||(b.call(this,a,0,0),c.onload=null,c.onerror=null,delete c)};c.src=a;c.complete&&(d=!0,c.onload=null,c.onerror=null,c.width&&c.height?b.call(this,a,c.width,c.height):b.call(this,a,0,0),delete c)},FanweShou.showLogin=function(){FanweShou.isCancel||(FanweShou.LoginPageIsShow=!0,FanweShou.ShouIframe.style.display="block",FanweShou.CheckPageBox.style.display="none",FanweShou.ShouIframe.src=FanweShou.url+"shou.php?href="+encodeURIComponent(window.location.href)+"&t="+(new Date).getTime())},
FanweShou.checkPage=function(){var a=document.head||document.getElementsByTagName("head")[0],b=document.createElement("script");b.type="text/javascript";b.src=FanweShou.url+"services/service.php?m=shou&a=init&url="+encodeURIComponent(window.location.href)+"&callback=FanweShou.checkResult&t="+(new Date).getTime();a.appendChild(b)},FanweShou.checkResult=function(a){FanweShou.isCancel||(0==a.uid?FanweShou.LoginPageIsShow||FanweShou.showLogin():1==a.goods?FanweShou.checkPublish("publish,g,"+a.status):
FanweShou.showImgs())}):(FanweShou.setCss(),document.getElementById("FST_LOGO")&&(document.getElementById("FST_LOGO").src=FanweShou.url+"shou/logo.png"),FanweShou.addIframeEvent())})();FanweShou.init();
